# Generated by Django 4.1 on 2022-08-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Ip адрес'),
        ),
    ]
