# Generated by Django 4.1 on 2022-08-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'quantity'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
